### ISSUE TITLE
Message sizes

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-mplex#107]
This module will [throw if it encounters messages bigger than 1MB](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/restrict-size.js#L3) but unless I'm reading it incorrectly `go-libp2p` [allows up to 4MB](https://github.com/libp2p/go-libp2p-core/blob/d143201d83c2cbb01ba15212d38531759fd15c0d/network/network.go#L23).

Should these not be the same?

**Comment by jacobheun** [comment]
Are you hitting issues? go-mplex itself is capped at 1MB https://github.com/libp2p/go-mplex/blob/master/multiplex.go#L20

You are linking to the go network code. I believe what go does is add a slight delay before sending in order to batch messages into a larger packet to send at once, rather than several smaller messages. When the larger message comes in, we will read the varint prefix of each bundled message and if that smaller message is larger than 1MB mplex will error. go-mplex should be restricting mplex messages to 1MB, but what goes over the wire could be 4MB.

**Comment by achingbrain** [comment]
Closing as not an issue
