### ISSUE TITLE
fix stream ids to match mplex protocol spec

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p-mplex#83]
In regards to https://github.com/ipfs/js-ipfs/issues/1601, it looks like streams id's are being set incorrectly. We need to make sure that stream id's match the spec, where initiator ids are odd and receiver id's are even. The js implementation currently has them backwards.

Spec: https://github.com/libp2p/mplex#protocol

**Comment by dryajov** [comment]
@jacobheun, there is already an issue documenting it here - https://github.com/libp2p/mplex/pull/3. I'm not sure why the fix to the spec wasn't merged (wording?). Bottom line, the spec was incorrect, since it was reverse engineered from the existing js code, and the id sequencing was interpreted incorrectly. I believe this fix has been already applied to the Go implementation (the js one _is correct_).

**Comment by dryajov** [comment]
Also, I've heard that this fixes the multiple interop issues with Go (@Stebalien is this the still the case?).

**Comment by Stebalien** [comment]
This should have been fixed and I believe the release has been fixed. Is this still an issue?

**Comment by Stebalien** [comment]
Ah, I need to merge that spec PR (and possibly update it). I'll take a look.

**Comment by dryajov** [comment]
Thanks, I think we never nailed down the correct wording, happy to wrap that up if its still an issue.

**Comment by Stebalien** [comment]
I merged that PR and submitted a new one with some final edits. Mind taking a look? https://github.com/libp2p/mplex/pull/5

**Comment by jacobheun** [comment]
@dryajov ah, that's great, thanks! Closing this.
