### ISSUE TITLE
Handle slow readers/writers

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p-mplex#85]
As mentioned in the spec implementation notes, https://github.com/libp2p/mplex/blob/1ceb5eaf0f352a6c81fd0ff5d25bfa0f2e4e4c53/README.md#implementation-notes, we need to make sure that we are properly handling slow readers/writers so we don't risk the whole multiplexer being blocked.

We should audit the implementation to make sure it is doing this, and if not, fix it.

*Reference*: https://github.com/libp2p/mplex/pull/5/files#r221765434 comment from @dryajov

**Comment by prophet1906** [comment]
Is there any workaround for now?

**Comment by betamos** [comment]
@prophet1906 there's a workaround in #108 if you want outbound back pressure to work (i.e. if the reader is slower than the sender).

**Comment by achingbrain** [comment]
Each stream has it's own input buffer so one slow stream reader doesn't block the rest of the streams.

If the input buffer reaches a configurable maximum the stream is reset, this is all we can do without protocol-level backpressure.

People should use Yamux instead since it has protocol-level backpressure by design.
